//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarWindowsClient.CarRentalWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarRentalWCFService.ICarRentalWCFService")]
    public interface ICarRentalWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalWCFService/RemoveCar", ReplyAction="http://tempuri.org/ICarRentalWCFService/RemoveCarResponse")]
        void RemoveCar(string RegNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarRentalWCFService/RemoveCar", ReplyAction="http://tempuri.org/ICarRentalWCFService/RemoveCarResponse")]
        System.Threading.Tasks.Task RemoveCarAsync(string RegNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarRentalWCFServiceChannel : RentalCarWindowsClient.CarRentalWCFService.ICarRentalWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarRentalWCFServiceClient : System.ServiceModel.ClientBase<RentalCarWindowsClient.CarRentalWCFService.ICarRentalWCFService>, RentalCarWindowsClient.CarRentalWCFService.ICarRentalWCFService {
        
        public CarRentalWCFServiceClient() {
        }
        
        public CarRentalWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarRentalWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarRentalWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarRentalWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RemoveCar(string RegNr) {
            base.Channel.RemoveCar(RegNr);
        }
        
        public System.Threading.Tasks.Task RemoveCarAsync(string RegNr) {
            return base.Channel.RemoveCarAsync(RegNr);
        }
    }
}
